### ISSUE TITLE
Load_More_bug

### ISSUE THREAD

**Issue by maxy4321** [iridiumdev/ird-explorer#4]
maybe this is a small bug, and maybe it's just in my browser. Checked in Chrome and Firefox,  situation is  same.
1. open https://explorer.ird.cash/#blockchain
2. go to down
3. waiting for the emergence of a new block.
4. block appears at  bottom, not at top.
5. after that,  button "Load More" does not work.
![load_more](https://user-images.githubusercontent.com/44919380/48299512-d2d48c00-e4f7-11e8-81b5-f2a568421177.jpg)

**Comment by danielclasen** [comment]
Thanks for the report and the good catch @maxy4321 I think the issue is fixed now and it is up to @stevebrush to merge my PR #5

-Daniel

**Comment by steevebrush** [comment]
Sure I will but not tonight :-)
(update) it appears that this doesn't resolve the issue but makes all the browers I tried hang ?
